name: flutter_issues_viewer
description: "An app to view issues on the Flutter repository"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  get_it: ^8.0.2
  http: ^1.2.2
  flutter_riverpod: ^2.5.1
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  mockito: ^5.4.4
  test: ^1.25.7

flutter:
  uses-material-design: true
