// Mocks generated by Mockito 5.4.4 from annotations
// in flutter_issues_viewer/test/mocks/services_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:flutter/material.dart' as _i1;
import 'package:flutter_issues_viewer/core/domain/base/base_net_response/base_net_response.dart'
    as _i3;
import 'package:flutter_issues_viewer/modules/data/models/issue_contracts.dart'
    as _i8;
import 'package:flutter_issues_viewer/modules/data/services/network/i_issues_network_service.dart'
    as _i6;
import 'package:flutter_issues_viewer/modules/domain/entities/issue.dart'
    as _i7;
import 'package:flutter_issues_viewer/navigation/navigation_service.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGlobalKey_0<T extends _i1.State<_i1.StatefulWidget>>
    extends _i2.SmartFake implements _i1.GlobalKey<T> {
  _FakeGlobalKey_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBaseNetResponse_1<Data> extends _i2.SmartFake
    implements _i3.BaseNetResponse<Data> {
  _FakeBaseNetResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [NavigationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNavigationService extends _i2.Mock implements _i4.NavigationService {
  @override
  _i1.GlobalKey<_i1.NavigatorState> get navigatorKey => (super.noSuchMethod(
        Invocation.getter(#navigatorKey),
        returnValue: _FakeGlobalKey_0<_i1.NavigatorState>(
          this,
          Invocation.getter(#navigatorKey),
        ),
        returnValueForMissingStub: _FakeGlobalKey_0<_i1.NavigatorState>(
          this,
          Invocation.getter(#navigatorKey),
        ),
      ) as _i1.GlobalKey<_i1.NavigatorState>);

  @override
  set navigatorKey(_i1.GlobalKey<_i1.NavigatorState>? _navigatorKey) =>
      super.noSuchMethod(
        Invocation.setter(
          #navigatorKey,
          _navigatorKey,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<dynamic> goTo(
    String? routeName, {
    dynamic arguments,
    bool? logRoute = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #goTo,
          [routeName],
          {
            #arguments: arguments,
            #logRoute: logRoute,
          },
        ),
        returnValue: _i5.Future<dynamic>.value(),
        returnValueForMissingStub: _i5.Future<dynamic>.value(),
      ) as _i5.Future<dynamic>);

  @override
  void goBack([dynamic arguments]) => super.noSuchMethod(
        Invocation.method(
          #goBack,
          [arguments],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> loaderScreen({required bool? show}) => (super.noSuchMethod(
        Invocation.method(
          #loaderScreen,
          [],
          {#show: show},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [IIssuesNetworkService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIIssuesNetworkService extends _i2.Mock
    implements _i6.IIssuesNetworkService {
  @override
  _i5.Future<_i3.BaseNetResponse<List<_i7.Issue>>> issues({
    bool? isPaginated = true,
    int? pageNumber = 1,
    _i8.IssuesFilterBy? filterBy = _i8.IssuesFilterBy.assigned,
    _i8.IssuesSortBy? sortBy = _i8.IssuesSortBy.created,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #issues,
          [],
          {
            #isPaginated: isPaginated,
            #pageNumber: pageNumber,
            #filterBy: filterBy,
            #sortBy: sortBy,
          },
        ),
        returnValue: _i5.Future<_i3.BaseNetResponse<List<_i7.Issue>>>.value(
            _FakeBaseNetResponse_1<List<_i7.Issue>>(
          this,
          Invocation.method(
            #issues,
            [],
            {
              #isPaginated: isPaginated,
              #pageNumber: pageNumber,
              #filterBy: filterBy,
              #sortBy: sortBy,
            },
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.BaseNetResponse<List<_i7.Issue>>>.value(
                _FakeBaseNetResponse_1<List<_i7.Issue>>(
          this,
          Invocation.method(
            #issues,
            [],
            {
              #isPaginated: isPaginated,
              #pageNumber: pageNumber,
              #filterBy: filterBy,
              #sortBy: sortBy,
            },
          ),
        )),
      ) as _i5.Future<_i3.BaseNetResponse<List<_i7.Issue>>>);
}
