name: Flutter Firebase Deployment

on:
  push:
    branches:
      - main # Deploy only on pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 'stable'

    - name: Install Dependencies
      run: flutter pub get

    - name: Build AppBundle
      run: flutter build appbundle --release

    - name: Set up Firebase CLI
      uses: w9jds/firebase-action@v2.2.0
      with:
        args: firebase setup:emulators:ui

    - name: Deploy AppBundle to Firebase App Distribution
      env:
        FIREBASE_AUTH_TOKEN: ${{ secrets.FIREBASE_AUTH_TOKEN }}
      run: |
        firebase appdistribution:distribute \
          build/app/outputs/bundle/release/app-release.aab \
          --app 1:627150186670:android:4759a8ed8efae1c52fe53f \
          --groups MediaMarket
