name: Flutter Firebase Deployment

on:
  push:
    branches:
      - main # Deploy only on pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.5'

    - name: Install Dependencies
      run: flutter pub get

    - name: Decode Android keystore
      run: echo "${{ secrets.ANDROID_KEY_STORE }}" | base64 --decode > android/app/upload-keystore.jks

    - name: Decode Android key properties
      run: echo "${{ secrets.ANDROID_KEY_PROPERTIES }}" | base64 --decode > android/key.properties

    # - name: Install Firebase CLI
    #   run: |
    #     curl -sL https://firebase.tools | bash
    #     firebase --version
  
    # - name: Authenticate with GCP
    #   run: |
    #     echo "${{ secrets.GCP_SA_KEY }}" > $HOME/gcloud-key.json
    #     export GOOGLE_APPLICATION_CREDENTIALS="$HOME/gcloud-key.json"

    # - name: Debug Firebase Auth Token
    #   run: |
    #     echo "Auth token length: ${#FIREBASE_AUTH_TOKEN}" && echo "Auth token starts with: ${FIREBASE_AUTH_TOKEN:0:10}"
    #   env:
    #     FIREBASE_AUTH_TOKEN: ${{ secrets.FIREBASE_AUTH_TOKEN }}

    - name: Build AppBundle
      run: flutter build appbundle --release

    - name: Upload generated aab to the artifacts
      uses: actions/upload-artifact@master
      with:
        name: app-release.aab
        path: build/app/outputs/bundle/release/app-release.aab

    - name: Distribute apk to Firebase App Distribution
      uses: wzieba/Firebase-Distribution-Github-Action@v1
      with:
        appId: ${{ secrets.FIREBASE_APP_ID }}
        serviceCredentialsFileContent: ${{ secrets.GCP_SA_KEY }}
        groups: MediaMarket
        file: build/app/outputs/bundle/release/app-release.aab